
# New Recording
walk_sleep('0.389')
walk_send('s', "Down")
walk_sleep('2.041')
walk_send('s', "Up")

# New Recording

# New Recording
walk_sleep('7.902')
walk_send('d', "Down")
walk_sleep('0.117')
walk_send("'d'", "Up")
walk_sleep('0.027')
walk_send('a', "Down")
walk_sleep('0.1')
walk_send('s', "Down")
walk_sleep('0.051')
walk_send("'a'", "Up")
walk_sleep('0.041')
walk_send('d', "Down")
walk_sleep('0.009')
walk_send("'s'", "Up")
walk_sleep('0.317')
walk_send("'d'", "Up")

# New Recording
walk_sleep('2.22')
walk_send("'\x03'", "Up")
walk_sleep('0.201')
walk_send("Key.ctrl_l", "Up")
walk_sleep('0.176')
walk_send(Key.ctrl_l, "Down")
walk_sleep('0.121')
walk_send('\x03', "Down")
walk_sleep('0.145')
walk_send("'\x03'", "Up")
walk_sleep('0.166')
walk_send("Key.ctrl_l", "Up")
walk_sleep('0.457')
walk_send(Key.ctrl_l, "Down")
walk_sleep('0.243')
walk_send('\x03', "Down")
walk_sleep('0.071')
walk_send("'\x03'", "Up")
walk_sleep('0.273')
walk_send("Key.ctrl_l", "Up")
