import sys
sys.dont_write_bytecode = True
from settings import *

focus_roblox()
print("started")
walk_sleep('0.899')
walk_send('a', "Down")
walk_sleep('2.541')
walk_send('a', "Up")
walk_sleep('0.746')
walk_send('s', "Down")
walk_sleep('5.931')
walk_send('s', "Up")
walk_sleep('0.012')
walk_send('s', "Down")
walk_sleep('0.003')
walk_send('s', "Up")
walk_sleep('0.517')
walk_send('d', "Down")
walk_sleep('1.687')
walk_send('d', "Up")
walk_sleep('0.518')
walk_send('a', "Down")
walk_sleep('0.181')
walk_send('a', "Up")
walk_sleep('0.172')
walk_send('w', "Down")
walk_sleep('0.166')
walk_send('w', "Up")
walk_sleep('0.17')
walk_send('d', "Down")
walk_sleep('0.006')
walk_send("space", "Down")
walk_sleep('0.203')
walk_send("space", "Up")
walk_sleep('0.314')
walk_send('d', "Up")
walk_sleep('0.192')
walk_send('s', "Down")
walk_sleep('1.835')
walk_send('s', "Up")
walk_sleep('0.4')
walk_send('a', "Down")
walk_sleep('0.662')
walk_send('a', "Up")
walk_sleep('0.582')
walk_send('s', "Down")
walk_sleep('5.363')
walk_send('s', "Up")
walk_sleep('0.802')
walk_send('a', "Down")
walk_sleep('1.686')
walk_send('a', "Up")
walk_sleep('0.979')
walk_send('s', "Down")
walk_sleep('2.15')
walk_send('s', "Up")
walk_sleep('0.853')
walk_send('a', "Down")
walk_sleep('1.187')
walk_send('a', "Up")
walk_sleep('0.259')
walk_send('s', "Down")
walk_sleep('1.631')
walk_send('s', "Up")
walk_sleep('0.456')
walk_send('s', "Down")
walk_sleep('0.387')
walk_send('s', "Up")
walk_sleep('0.217')
walk_send('d', "Down")
walk_sleep('0.161')
walk_send('d', "Up")
walk_sleep('0.167')
walk_send('w', "Down")
walk_sleep('0.157')
walk_send('w', "Up")
walk_sleep('0.26')
walk_send('a', "Down")
walk_sleep('0.006')
walk_send("space", "Down")
walk_sleep('0.154')
walk_send("space", "Up")
walk_sleep('1.506')
walk_send('a', "Up")
walk_sleep('0.237')
walk_send('s', "Down")
walk_sleep('0.255')
walk_send("space", "Down")
walk_sleep('0.166')
walk_send("space", "Up")
walk_sleep('0.928')
walk_send('s', "Up")
walk_sleep('0.285')
walk_send('a', "Down")
walk_sleep('1.614')
walk_send('a', "Up")
walk_sleep('0.718')
walk_send('s', "Down")
walk_sleep('1.302')
walk_send('s', "Up")
walk_sleep('3.3')
walk_send('a', "Down")
walk_sleep('0.988')
walk_send('a', "Up")
walk_sleep('0.721')
walk_send('f', "Down")
walk_sleep('0.121')
walk_send('f', "Up")
print("finished")